cards = [
    {"title":"as", "type":"trèfle", "value":"1 ou 11"},
    {"title":"as", "type":"coeur", "value":"1 ou 11"},
    {"title":"as", "type":"pique", "value":"1 ou 11"},
    {"title":"as", "type":"carreau", "value":"1 ou 11"},
    {"title":"2", "type":"trèfle", "value":"2"},
    {"title":"2", "type":"coeur", "value":"2"},
    {"title":"2", "type":"pique", "value":"2"},
    {"title":"2", "type":"carreau", "value":"2"},
    {"title":"3", "type":"trèfle", "value":"3"},
    {"title":"3", "type":"coeur", "value":"3"},
    {"title":"3", "type":"pique", "value":"3"},
    {"title":"3", "type":"carreau", "value":"3"},
    {"title":"4", "type":"trèfle", "value":"4"},
    {"title":"4", "type":"coeur", "value":"4"},
    {"title":"4", "type":"pique", "value":"4"},
    {"title":"4", "type":"carreau", "value":"4"},
    {"title":"5", "type":"trèfle", "value":"5"},
    {"title":"5", "type":"coeur", "value":"5"},
    {"title":"5", "type":"pique", "value":"5"},
    {"title":"5", "type":"carreau", "value":"5"},
    {"title":"6", "type":"trèfle", "value":"6"},
    {"title":"6", "type":"coeur", "value":"6"},
    {"title":"6", "type":"pique", "value":"6"},
    {"title":"6", "type":"carreau", "value":"6"},
    {"title":"7", "type":"trèfle", "value":"7"},
    {"title":"7", "type":"coeur", "value":"7"},
    {"title":"7", "type":"pique", "value":"7"},
    {"title":"7", "type":"carreau", "value":"7"},
    {"title":"8", "type":"trèfle", "value":"8"},
    {"title":"8", "type":"coeur", "value":"8"},
    {"title":"8", "type":"pique", "value":"8"},
    {"title":"8", "type":"carreau", "value":"8"},
    {"title":"9", "type":"trèfle", "value":"9"},
    {"title":"9", "type":"coeur", "value":"9"},
    {"title":"9", "type":"pique", "value":"9"},
    {"title":"9", "type":"carreau", "value":"9"},
    {"title":"10", "type":"trèfle", "value":"10"},
    {"title":"10", "type":"coeur", "value":"10"},
    {"title":"10", "type":"pique", "value":"10"},
    {"title":"10", "type":"carreau", "value":"10"},
    {"title":"valet", "type":"trèfle", "value":"10"},
    {"title":"valet", "type":"coeur", "value":"10"},
    {"title":"valet", "type":"pique", "value":"10"},
    {"title":"valet", "type":"carreau", "value":"10"},
    {"title":"reine", "type":"trèfle", "value":"10"},
    {"title":"reine", "type":"coeur", "value":"10"},
    {"title":"reine", "type":"pique", "value":"10"},
    {"title":"reine", "type":"carreau", "value":"10"},
    {"title":"roi", "type":"trèfle", "value":"10"},
    {"title":"roi", "type":"coeur", "value":"10"},
    {"title":"roi", "type":"pique", "value":"10"},
    {"title":"roi", "type":"carreau", "value":"10"},
]